import { Facility, Covenant, Amendment, ActivityLogEntry, Document } from './types';

export const mockCovenants: Covenant[] = [
  {
    id: 'cov-1',
    name: 'Leverage Ratio',
    type: 'financial',
    threshold: 'Total Debt / EBITDA ≤ 4.50x',
    frequency: 'quarterly',
    status: 'compliant',
    currentValue: '3.82x',
    lastTested: '2025-12-31',
    nextTestDate: '2026-03-31',
    dependencies: ['cov-2', 'cov-3'],
    description: 'The ratio of consolidated total debt to consolidated EBITDA shall not exceed 4.50 to 1.00.',
    legalReference: 'Section 7.01(a)',
    materiality: 'high',
    confidence: 95,
  },
  {
    id: 'cov-2',
    name: 'Interest Coverage',
    type: 'financial',
    threshold: 'EBITDA / Interest Expense ≥ 3.00x',
    frequency: 'quarterly',
    status: 'compliant',
    currentValue: '4.25x',
    lastTested: '2025-12-31',
    nextTestDate: '2026-03-31',
    dependencies: [],
    description: 'The ratio of consolidated EBITDA to consolidated interest expense shall not be less than 3.00 to 1.00.',
    legalReference: 'Section 7.01(b)',
    materiality: 'high',
    confidence: 92,
  },
  {
    id: 'cov-3',
    name: 'Minimum Liquidity',
    type: 'financial',
    threshold: 'Cash + Availability ≥ $50M',
    frequency: 'monthly',
    status: 'at-risk',
    currentValue: '$58M',
    lastTested: '2026-01-05',
    nextTestDate: '2026-02-05',
    dependencies: [],
    description: 'The borrower shall maintain minimum liquidity of not less than $50,000,000 at all times.',
    legalReference: 'Section 7.01(c)',
    materiality: 'high',
    confidence: 78,
  },
  {
    id: 'cov-4',
    name: 'Capital Expenditure Limit',
    type: 'negative',
    threshold: 'CapEx ≤ $25M per fiscal year',
    frequency: 'annual',
    status: 'compliant',
    currentValue: '$18.5M YTD',
    lastTested: '2025-12-31',
    nextTestDate: '2026-12-31',
    dependencies: ['cov-1'],
    description: 'Capital expenditures shall not exceed $25,000,000 in any fiscal year.',
    legalReference: 'Section 7.02(f)',
    materiality: 'medium',
    confidence: 98,
  },
  {
    id: 'cov-5',
    name: 'Dividend Restriction',
    type: 'negative',
    threshold: 'No dividends if Leverage > 3.50x',
    frequency: 'ongoing',
    status: 'compliant',
    dependencies: ['cov-1'],
    description: 'No restricted payments if leverage ratio exceeds 3.50 to 1.00.',
    legalReference: 'Section 7.02(g)',
    materiality: 'medium',
    confidence: 95,
  },
  {
    id: 'cov-6',
    name: 'Quarterly Financials',
    type: 'reporting',
    threshold: 'Delivery within 45 days of quarter end',
    frequency: 'quarterly',
    status: 'compliant',
    lastTested: '2025-12-31',
    nextTestDate: '2026-02-14',
    dependencies: [],
    description: 'Deliver quarterly financial statements within 45 days after the end of each fiscal quarter.',
    legalReference: 'Section 6.01(b)',
    materiality: 'medium',
    confidence: 100,
  },
  {
    id: 'cov-7',
    name: 'Annual Audit',
    type: 'reporting',
    threshold: 'Audited financials within 90 days of FYE',
    frequency: 'annual',
    status: 'pending',
    nextTestDate: '2026-03-31',
    dependencies: ['cov-6'],
    description: 'Deliver annual audited financial statements within 90 days after fiscal year end.',
    legalReference: 'Section 6.01(a)',
    materiality: 'high',
    confidence: 88,
  },
  {
    id: 'cov-8',
    name: 'Insurance Maintenance',
    type: 'affirmative',
    threshold: 'Maintain adequate insurance coverage',
    frequency: 'ongoing',
    status: 'compliant',
    dependencies: [],
    description: 'Maintain insurance with responsible carriers covering risks and in amounts customary for the industry.',
    legalReference: 'Section 6.05',
    materiality: 'low',
    confidence: 90,
  },
];

export const mockAmendments: Amendment[] = [
  {
    id: 'amd-1',
    title: 'First Amendment - Leverage Covenant Relief',
    effectiveDate: '2025-06-15',
    documentId: 'doc-3',
    summary: 'Temporarily increased leverage covenant from 4.00x to 4.50x through Q4 2025.',
    impactedCovenants: ['cov-1', 'cov-5'],
    changeType: 'modification',
    status: 'executed',
    requestedBy: 'Borrower',
  },
  {
    id: 'amd-2',
    title: 'Second Amendment - Liquidity Definition',
    effectiveDate: '2025-09-30',
    documentId: 'doc-4',
    summary: 'Revised definition of "Minimum Liquidity" to include undrawn revolver availability.',
    impactedCovenants: ['cov-3'],
    changeType: 'modification',
    status: 'executed',
    requestedBy: 'Borrower',
  },
  {
    id: 'amd-3',
    title: 'Q4 2025 Compliance Certificate Waiver',
    effectiveDate: '2026-01-10',
    documentId: 'doc-5',
    summary: 'Extension of quarterly compliance certificate delivery deadline by 15 days.',
    impactedCovenants: ['cov-6'],
    changeType: 'waiver',
    status: 'pending',
    requestedBy: 'Borrower',
  },
];

export const mockFacilities: Facility[] = [
  {
    id: 'fac-1',
    name: 'Senior Secured Credit Facility',
    borrower: 'Acme Industrial Holdings, Inc.',
    agent: 'JPMorgan Chase Bank, N.A.',
    currency: 'USD',
    amount: 500000000,
    status: 'active',
    closingDate: '2024-03-15',
    maturityDate: '2029-03-15',
    covenants: mockCovenants,
    amendments: mockAmendments,
    lenders: [
      { id: 'lend-1', name: 'JPMorgan Chase Bank, N.A.', commitment: 125000000, share: 25, role: 'agent' },
      { id: 'lend-2', name: 'Bank of America, N.A.', commitment: 100000000, share: 20, role: 'lead' },
      { id: 'lend-3', name: 'Wells Fargo Bank, N.A.', commitment: 75000000, share: 15, role: 'participant' },
      { id: 'lend-4', name: 'Citibank, N.A.', commitment: 75000000, share: 15, role: 'participant' },
      { id: 'lend-5', name: 'Goldman Sachs Bank USA', commitment: 62500000, share: 12.5, role: 'participant' },
      { id: 'lend-6', name: 'Morgan Stanley Bank, N.A.', commitment: 62500000, share: 12.5, role: 'participant' },
    ],
    complianceScore: 87,
    lastUpdated: '2026-01-10T14:30:00Z',
  },
  {
    id: 'fac-2',
    name: 'Term Loan B Facility',
    borrower: 'Phoenix Technologies Corp.',
    agent: 'Credit Suisse AG',
    currency: 'USD',
    amount: 350000000,
    status: 'active',
    closingDate: '2024-06-20',
    maturityDate: '2031-06-20',
    covenants: mockCovenants.slice(0, 5),
    amendments: [],
    lenders: [
      { id: 'lend-7', name: 'Credit Suisse AG', commitment: 87500000, share: 25, role: 'agent' },
      { id: 'lend-8', name: 'Deutsche Bank AG', commitment: 70000000, share: 20, role: 'lead' },
      { id: 'lend-9', name: 'Barclays Bank PLC', commitment: 70000000, share: 20, role: 'participant' },
    ],
    complianceScore: 94,
    lastUpdated: '2026-01-08T09:15:00Z',
  },
  {
    id: 'fac-3',
    name: 'ABL Revolving Credit Facility',
    borrower: 'Meridian Retail Group LLC',
    agent: 'Bank of America, N.A.',
    currency: 'USD',
    amount: 150000000,
    status: 'active',
    closingDate: '2025-01-10',
    maturityDate: '2030-01-10',
    covenants: mockCovenants.slice(2, 6),
    amendments: mockAmendments.slice(0, 1),
    lenders: [
      { id: 'lend-10', name: 'Bank of America, N.A.', commitment: 75000000, share: 50, role: 'agent' },
      { id: 'lend-11', name: 'PNC Bank, N.A.', commitment: 37500000, share: 25, role: 'participant' },
      { id: 'lend-12', name: 'Fifth Third Bank', commitment: 37500000, share: 25, role: 'participant' },
    ],
    complianceScore: 72,
    lastUpdated: '2026-01-12T11:45:00Z',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'Credit Agreement - Acme Industrial Holdings',
    type: 'facility-agreement',
    uploadedAt: '2024-03-15T10:00:00Z',
    uploadedBy: 'Sarah Mitchell',
    status: 'approved',
    covenantCount: 8,
  },
  {
    id: 'doc-2',
    name: 'Compliance Certificate Q3 2025',
    type: 'compliance-certificate',
    uploadedAt: '2025-11-14T09:30:00Z',
    uploadedBy: 'Michael Chen',
    status: 'approved',
  },
  {
    id: 'doc-3',
    name: 'First Amendment to Credit Agreement',
    type: 'amendment',
    uploadedAt: '2025-06-15T14:20:00Z',
    uploadedBy: 'Sarah Mitchell',
    status: 'approved',
    covenantCount: 2,
  },
  {
    id: 'doc-4',
    name: 'Second Amendment to Credit Agreement',
    type: 'amendment',
    uploadedAt: '2025-09-30T11:00:00Z',
    uploadedBy: 'Sarah Mitchell',
    status: 'approved',
    covenantCount: 1,
  },
  {
    id: 'doc-5',
    name: 'Waiver Request - Q4 Compliance Certificate',
    type: 'waiver',
    uploadedAt: '2026-01-08T16:45:00Z',
    uploadedBy: 'Michael Chen',
    status: 'reviewed',
    covenantCount: 1,
  },
];

export const mockActivityLog: ActivityLogEntry[] = [
  {
    id: 'act-1',
    timestamp: '2026-01-12T11:45:00Z',
    action: 'Compliance state updated',
    actor: 'System',
    entity: 'Facility',
    entityId: 'fac-3',
    details: 'Minimum Liquidity covenant status changed from Compliant to At Risk',
    category: 'compliance',
  },
  {
    id: 'act-2',
    timestamp: '2026-01-10T14:30:00Z',
    action: 'Document uploaded',
    actor: 'Michael Chen',
    entity: 'Document',
    entityId: 'doc-5',
    details: 'Waiver Request - Q4 Compliance Certificate uploaded for review',
    category: 'document',
  },
  {
    id: 'act-3',
    timestamp: '2026-01-08T09:15:00Z',
    action: 'Amendment approved',
    actor: 'Sarah Mitchell',
    entity: 'Amendment',
    entityId: 'amd-2',
    details: 'Second Amendment - Liquidity Definition marked as executed',
    category: 'amendment',
  },
  {
    id: 'act-4',
    timestamp: '2026-01-05T16:00:00Z',
    action: 'Buyer access granted',
    actor: 'James Wilson',
    entity: 'Facility',
    entityId: 'fac-1',
    details: 'Read-only access granted to Blackstone Credit for due diligence (expires 2026-01-19)',
    category: 'access',
  },
  {
    id: 'act-5',
    timestamp: '2026-01-03T10:30:00Z',
    action: 'Covenant threshold updated',
    actor: 'System',
    entity: 'Covenant',
    entityId: 'cov-1',
    details: 'Leverage Ratio threshold reverted to 4.00x per amendment schedule',
    category: 'covenant',
  },
];
